name: CiTE
subtitle: Beta
description: A toolbox for digital pedagogy in composition, rhetoric, and literature
pygments: true
permalink: none
baseurl: /test

page1: introduction
page2: documentation
page3: teaching resources
page4: online tools