name: Pedagogy Toolkit
subtitle: for English
description: Community-driven resources for digital pedagogy in composition, rhetoric, and literature.
pygments: true
permalink: none
baseurl: /test

page1: welcome
page2: documentation
page3: teaching resources
page4: online tools